import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { get, send } from "./api";
import {
  ConfirmButton, EmptyState, Field, FormActions, Icon, JsonView, MetricCard,
  Modal, PageHeader, Panel, SearchBox, StatusPill, cx, submitForm,
} from "./components";
import type {
  AlertItem, AuditItem, Camera, ClusterResponse, Deployment, DiscoveryRun,
  DiscoveryScope, HealthResponse, NodeView, NotificationItem, Site, TelemetryResponse,
  ValidationAttempt,
} from "./types";

type Page = "overview" | "cameras" | "discovery" | "solutions" | "cluster" | "alerts" | "operations" | "settings";
interface Snapshot {
  health: HealthResponse | null;
  site: Site | null;
  cameras: Camera[];
  discovery: DiscoveryRun[];
  scopes: DiscoveryScope[];
  deployments: Deployment[];
  cluster: ClusterResponse | null;
  alerts: AlertItem[];
  audit: AuditItem[];
}
type Mutate = (promise: Promise<unknown>, success: string) => Promise<boolean>;

const emptySnapshot: Snapshot = { health: null, site: null, cameras: [], discovery: [], scopes: [], deployments: [], cluster: null, alerts: [], audit: [] };
const pages: Array<{ group: string; items: Array<{ id: Page; label: string; icon: string }> }> = [
  { group: "Operations", items: [
    { id: "overview", label: "Overview", icon: "overview" },
    { id: "cameras", label: "Cameras", icon: "camera" },
    { id: "discovery", label: "Discovery", icon: "radar" },
    { id: "solutions", label: "Solutions", icon: "boxes" },
  ] },
  { group: "Infrastructure", items: [
    { id: "cluster", label: "K3s cluster", icon: "cluster" },
    { id: "alerts", label: "Alerts", icon: "bell" },
    { id: "operations", label: "Activity", icon: "history" },
  ] },
  { group: "System", items: [{ id: "settings", label: "Settings", icon: "settings" }] },
];

const fmt = (value?: string | null) => value ? new Date(value).toLocaleString() : "—";
const relative = (value?: string | null) => {
  if (!value) return "Never";
  const seconds = Math.round((Date.now() - new Date(value).getTime()) / 1000);
  if (seconds < 60) return `${Math.max(0, seconds)}s ago`;
  if (seconds < 3600) return `${Math.round(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.round(seconds / 3600)}h ago`;
  return `${Math.round(seconds / 86400)}d ago`;
};
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase());

async function safeGet<T>(path: string, fallback: T): Promise<T> {
  try { return await get<T>(path); } catch { return fallback; }
}

function DataTable({ headers, children }: { headers: string[]; children: ReactNode }) {
  return <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
}

function OverviewPage({ data, go }: { data: Snapshot; go: (page: Page) => void }) {
  const components = data.health?.components || {};
  const online = data.cameras.filter((camera) => camera.state === "online").length;
  const readyDeployments = data.cluster?.workloads.deployments.items.filter((item) => item.ready).length || 0;
  const activeAlerts = data.alerts.filter((item) => item.state !== "resolved");
  const componentRows = Object.entries(components);
  return <>
    <PageHeader eyebrow="Edge control center" title="System overview" description="A live view of this site's cameras, workloads, host services, and K3s runtime." />
    <div className="hero-status">
      <div className="hero-mark"><Icon name={data.health?.status === "healthy" ? "check" : "warning"} size={24} /></div>
      <div><span>Overall status</span><h2>{data.health ? title(data.health.status) : "Connecting to edge service"}</h2><p>{data.site ? `${data.site.display_name} · ${data.site.edge_id}` : "Waiting for site configuration"}</p></div>
      {data.health && <StatusPill value={data.health.status} />}
    </div>
    <div className="metric-grid four">
      <MetricCard label="Cameras online" value={`${online}/${data.cameras.length}`} hint={`${data.cameras.filter((item) => item.enabled).length} enabled`} status={components.camera_validation?.status} icon="camera" />
      <MetricCard label="Workloads ready" value={`${readyDeployments}/${data.cluster?.workloads.deployments.total || 0}`} hint={`${data.cluster?.workloads.pods.total || 0} pods`} status={components.workloads?.status} icon="boxes" />
      <MetricCard label="Active alerts" value={activeAlerts.length} hint={`${activeAlerts.filter((item) => item.severity === "critical").length} critical`} status={activeAlerts.some((item) => item.severity === "critical") ? "degraded" : "healthy"} icon="bell" />
      <MetricCard label="K3s node" value={`${data.cluster?.nodes.items.filter((item) => item.ready).length || 0}/${data.cluster?.nodes.total || 0}`} hint={data.cluster?.nodes.items[0]?.hardware_profile || "No profile"} status={components.node?.status} icon="cluster" />
    </div>
    <div className="content-grid two-one">
      <Panel title="Component health" subtitle="Independent services stay visible during a K3s outage">
        <div className="health-list">{componentRows.length ? componentRows.map(([name, component]) => <button className="health-row" key={name} onClick={() => go(name.includes("camera") ? "cameras" : name.includes("workload") || name.includes("node") || name.includes("k3s") ? "cluster" : "overview")}><span className="health-name"><i className={cx("health-dot", component.status)} />{title(name)}</span><StatusPill value={component.status} /><Icon name="arrow" size={16} /></button>) : <EmptyState title="Health unavailable" description="The edge service has not returned a health snapshot yet." />}</div>
      </Panel>
      <Panel title="Attention needed" subtitle="Current operational exceptions">
        <div className="attention-list">
          {activeAlerts.slice(0, 4).map((alert) => <button key={alert.alert_id} onClick={() => go("alerts")}><span className={cx("severity-bar", alert.severity)} /><span><strong>{alert.annotations.summary || alert.alertname}</strong><small>{alert.camera_id || alert.service || "System"} · {relative(alert.last_seen_at)}</small></span><StatusPill value={alert.severity} /></button>)}
          {!activeAlerts.length && <EmptyState icon="check" title="Nothing needs attention" description="No active alerts are currently recorded." />}
        </div>
      </Panel>
    </div>
    <Panel title="Camera estate" subtitle="Validation and configuration state across the site" action={<button className="text-button" onClick={() => go("cameras")}>View all <Icon name="arrow" size={15} /></button>}>
      {data.cameras.length ? <div className="camera-strip">{data.cameras.slice(0, 8).map((camera) => <button key={camera.camera_id} onClick={() => go("cameras")}><span className="camera-glyph"><Icon name="camera" /></span><span><strong>{camera.friendly_name}</strong><small>{camera.camera_id}</small></span><StatusPill value={camera.state} /></button>)}</div> : <EmptyState icon="camera" title="No cameras configured" description="Start a discovery run or add a camera manually." action={<button className="button" onClick={() => go("discovery")}>Start discovery</button>} />}
    </Panel>
  </>;
}

function CameraCreateModal({ close, mutate }: { close: () => void; mutate: Mutate }) {
  return <Modal title="Add camera" description="Create a provisional camera record. Credentials are entered separately." onClose={close}><form className="form-grid" onSubmit={(event) => submitForm(event, async (form) => {
    if (await mutate(send("/api/v1/cameras", "POST", { camera_id: form.get("camera_id"), friendly_name: form.get("friendly_name"), manufacturer: form.get("manufacturer") || null, model: form.get("model") || null, identifiers: [] }), "Camera added")) close();
  })}><Field label="Camera ID"><input name="camera_id" pattern="[a-z0-9][a-z0-9.-]*" placeholder="camera-01" required /></Field><Field label="Friendly name"><input name="friendly_name" placeholder="Main entrance entry" required /></Field><Field label="Manufacturer"><input name="manufacturer" placeholder="Optional" /></Field><Field label="Model"><input name="model" placeholder="Optional" /></Field><FormActions><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button" type="submit">Add camera</button></FormActions></form></Modal>;
}

function CameraDetail({ cameraId, close, mutate }: { cameraId: string; close: () => void; mutate: Mutate }) {
  const [camera, setCamera] = useState<Camera | null>(null);
  const [attempts, setAttempts] = useState<ValidationAttempt[]>([]);
  const [tab, setTab] = useState("overview");
  const load = useCallback(async () => {
    setCamera(await get<Camera>(`/api/v1/cameras/${encodeURIComponent(cameraId)}`));
    setAttempts(await safeGet(`/api/v1/cameras/${encodeURIComponent(cameraId)}/validation-attempts`, []));
  }, [cameraId]);
  useEffect(() => { void load(); }, [load]);
  const action = async (promise: Promise<unknown>, message: string) => { const succeeded = await mutate(promise, message); if (succeeded) await load(); return succeeded; };
  return <div className="drawer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && close()}><aside className="drawer">{!camera ? <div className="drawer-loading">Loading camera…</div> : <>
    <header className="drawer-head"><div className="camera-title"><span className="camera-glyph large"><Icon name="camera" size={23} /></span><div><span>{camera.camera_id}</span><h2>{camera.friendly_name}</h2></div></div><button className="icon-button" onClick={close}><Icon name="close" /></button></header>
    <div className="drawer-summary"><StatusPill value={camera.state} /><span>{camera.manufacturer || "Unknown vendor"} {camera.model || ""}</span><span>Updated {relative(camera.updated_at)}</span></div>
    <nav className="tabs">{["overview", "stream", "credentials", "history"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{title(item)}</button>)}</nav>
    <div className="drawer-body">
      {tab === "overview" && <><div className="detail-grid"><div><span>Enabled</span><strong>{camera.enabled ? "Yes" : "No"}</strong></div><div><span>Credentials</span><strong>{camera.credentials_configured ? "Configured" : "Not configured"}</strong></div><div><span>Validation</span><strong>{camera.validation_code || "Not run"}</strong></div><div><span>Last validated</span><strong>{relative(camera.last_validated_at)}</strong></div></div><div className="button-row"><button className="button" onClick={() => void action(send(`/api/v1/cameras/${encodeURIComponent(camera.camera_id)}/validate`, "POST"), "Validation queued")}>Validate now</button><button className="button secondary" onClick={() => void action(send(`/api/v1/cameras/${encodeURIComponent(camera.camera_id)}/enabled`, "PATCH", { enabled: !camera.enabled }), camera.enabled ? "Camera disabled" : "Camera enabled")}>{camera.enabled ? "Disable" : "Enable"}</button></div><h3>Identifiers</h3><div className="tag-list">{camera.identifiers.map((item) => <span key={`${item.kind}-${item.value}`}>{item.kind}: {item.value}</span>)}{!camera.identifiers.length && <span>No strong identifiers</span>}</div><h3>Assignments</h3>{camera.assignments?.length ? camera.assignments.map((item) => <div className="line-item" key={item.deployment_id}><strong>{item.deployment_id}</strong><span>{item.apps.join(", ")} · {item.fps} FPS</span></div>) : <p className="muted">No active assignments.</p>}</>}
      {tab === "stream" && <form className="form-grid" onSubmit={(event) => submitForm(event, async (form) => { await action(send(`/api/v1/cameras/${encodeURIComponent(camera.camera_id)}/stream`, "PUT", { scheme: form.get("scheme"), host: form.get("host"), port: Number(form.get("port")), path: form.get("path"), profile_token: form.get("profile_token"), transport: form.get("transport"), codec: form.get("codec") || null, width: form.get("width") ? Number(form.get("width")) : null, height: form.get("height") ? Number(form.get("height")) : null, fps: form.get("fps") ? Number(form.get("fps")) : null }), "Stream configuration saved"); })}><Field label="Scheme"><select name="scheme" defaultValue={camera.selected_profile?.scheme || "rtsp"}><option>rtsp</option><option>rtsps</option></select></Field><Field label="Transport"><select name="transport" defaultValue={camera.selected_profile?.transport || "tcp"}><option>tcp</option><option>udp</option></select></Field><Field label="Host" wide><input name="host" defaultValue={camera.selected_profile?.host || ""} placeholder="192.168.20.11" required /></Field><Field label="Port"><input name="port" type="number" defaultValue={camera.selected_profile?.port || 554} required /></Field><Field label="Profile token"><input name="profile_token" defaultValue={camera.selected_profile?.profile_token || "main"} required /></Field><Field label="Path" wide><input name="path" defaultValue={camera.selected_profile?.path || "/live/main"} required /></Field><Field label="Codec"><input name="codec" defaultValue={camera.selected_profile?.codec || ""} placeholder="h264" /></Field><Field label="FPS"><input name="fps" type="number" step="0.1" defaultValue={camera.selected_profile?.fps || ""} /></Field><Field label="Width"><input name="width" type="number" defaultValue={camera.selected_profile?.width || ""} /></Field><Field label="Height"><input name="height" type="number" defaultValue={camera.selected_profile?.height || ""} /></Field><FormActions><button className="button" type="submit">Save stream</button></FormActions></form>}
      {tab === "credentials" && <><div className="security-note"><Icon name="eye" /><span>Credentials are write-only. Existing values are never returned to this browser.</span></div><form className="form-grid" autoComplete="off" onSubmit={(event) => { const formElement = event.currentTarget; submitForm(event, async (form) => { if (await action(send(`/api/v1/cameras/${encodeURIComponent(camera.camera_id)}/credentials`, "PUT", { username: form.get("username") || null, password: form.get("password") || null, query: {} }), "Credentials replaced")) formElement.reset(); }); }}><Field label="Username" wide><input name="username" autoComplete="off" /></Field><Field label="Password" wide><input name="password" type="password" autoComplete="new-password" /></Field><FormActions><button className="button" type="submit">Replace credentials</button>{camera.credentials_configured && <ConfirmButton message="Permanently destroy the stored camera credentials?" onConfirm={() => { void action(send(`/api/v1/cameras/${encodeURIComponent(camera.camera_id)}/credentials`, "DELETE"), "Credentials cleared"); }}>Clear credentials</ConfirmButton>}</FormActions></form></>}
      {tab === "history" && <><h3>Validation attempts</h3>{attempts.length ? <div className="timeline">{attempts.map((item) => <div key={item.attempt_id}><i className={item.status} /><span><strong>{item.result_code || title(item.status)}</strong><small>{item.trigger} · {fmt(item.created_at)}</small></span></div>)}</div> : <p className="muted">No validation attempts.</p>}<h3>Discovery observations</h3>{camera.observations?.length ? <div className="timeline">{camera.observations.map((item) => <div key={item.observation_id}><i className={item.result_code === "OK" ? "succeeded" : "failed"} /><span><strong>{item.method} · {item.address}</strong><small>{item.result_code} · {fmt(item.observed_at)}</small></span></div>)}</div> : <p className="muted">No discovery observations.</p>}</>}
    </div>
  </>}</aside></div>;
}

function CamerasPage({ data, mutate }: { data: Snapshot; mutate: Mutate }) {
  const [query, setQuery] = useState(""); const [create, setCreate] = useState(false); const [selected, setSelected] = useState<string | null>(null);
  const filtered = data.cameras.filter((camera) => `${camera.camera_id} ${camera.friendly_name} ${camera.manufacturer} ${camera.model} ${camera.state}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="Camera management" title="Cameras" description="Onboard, validate, assign, and monitor every physical camera at this site." actions={<button className="button" onClick={() => setCreate(true)}><Icon name="plus" /> Add camera</button>} />
    <div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search cameras" /><div className="filter-summary"><StatusPill value="online" label={`${data.cameras.filter((item) => item.state === "online").length} online`} /><StatusPill value="offline" label={`${data.cameras.filter((item) => ["offline", "invalid"].includes(item.state)).length} attention`} /></div></div>
    <Panel className="flush">{filtered.length ? <DataTable headers={["Camera", "State", "Stream", "Credentials", "Last validated", ""]}>{filtered.map((camera) => <tr key={camera.camera_id}><td><button className="primary-cell" onClick={() => setSelected(camera.camera_id)}><span className="camera-glyph"><Icon name="camera" /></span><span><strong>{camera.friendly_name}</strong><small>{camera.camera_id} · {[camera.manufacturer, camera.model].filter(Boolean).join(" ") || "Unknown model"}</small></span></button></td><td><StatusPill value={camera.state} /></td><td><strong>{camera.selected_profile?.codec?.toUpperCase() || (camera.selected_profile_id ? "Configured" : "Not configured")}</strong><small className="table-sub">{camera.selected_profile?.width ? `${camera.selected_profile.width}×${camera.selected_profile.height}` : "—"}</small></td><td>{camera.credentials_configured ? <span className="check-label"><Icon name="check" size={15} /> Configured</span> : <span className="muted">Not configured</span>}</td><td>{relative(camera.last_validated_at)}<small className="table-sub">{camera.validation_code || "Not run"}</small></td><td><button className="icon-button" onClick={() => setSelected(camera.camera_id)}><Icon name="arrow" /></button></td></tr>)}</DataTable> : <EmptyState icon="camera" title="No matching cameras" description={data.cameras.length ? "Try a different search." : "Run discovery or add a camera manually."} />}</Panel>
    {create && <CameraCreateModal close={() => setCreate(false)} mutate={mutate} />}{selected && <CameraDetail cameraId={selected} close={() => setSelected(null)} mutate={mutate} />}
  </>;
}

function DiscoveryPage({ data, mutate }: { data: Snapshot; mutate: Mutate }) {
  const [scopeModal, setScopeModal] = useState(false); const active = data.discovery.find((item) => ["queued", "running"].includes(item.status));
  return <><PageHeader eyebrow="Camera onboarding" title="Discovery" description="Search only the approved interfaces and subnets, then track camera identity and validation." actions={<button className="button" disabled={Boolean(active) || !data.scopes.length} onClick={() => void mutate(send("/api/v1/discovery-runs", "POST"), "Discovery run queued")}><Icon name="radar" /> {active ? "Discovery running" : "Run discovery"}</button>} />
    {!data.scopes.length && <div className="callout warning"><Icon name="warning" /><div><strong>Discovery is not configured</strong><p>Add an allowlisted interface and subnet before starting a scan.</p></div><button className="button secondary" onClick={() => setScopeModal(true)}>Add scope</button></div>}
    <div className="content-grid two-one"><Panel title="Discovery scopes" subtitle="The worker cannot scan outside these boundaries" action={<button className="text-button" onClick={() => setScopeModal(true)}><Icon name="plus" /> Add</button>}><div className="scope-list">{data.scopes.map((scope) => <div key={scope.scope_id}><span className="scope-icon"><Icon name="radar" /></span><span><strong>{scope.cidr}</strong><small>{scope.interface_name} · RTSP {scope.rtsp_ports.join(", ")}</small></span><StatusPill value={scope.enabled} label={scope.enabled ? "Enabled" : "Disabled"} /></div>)}{!data.scopes.length && <EmptyState icon="radar" title="No discovery scopes" description="Configure the camera LAN boundary." />}</div></Panel><Panel title="Current state" subtitle="Most recent bounded operation">{active ? <div className="active-operation"><span className="spinner" /><h3>{title(active.status)}</h3><p>Operation {active.operation_id.slice(0, 8)}</p><div className="counter-grid">{Object.entries(active.counters || {}).map(([key, value]) => <div key={key}><strong>{value}</strong><span>{title(key)}</span></div>)}</div></div> : <EmptyState icon="check" title="Scanner idle" description="No discovery run is currently active." />}</Panel></div>
    <Panel title="Discovery history" subtitle="Recent candidate searches and their categorized results" className="flush">{data.discovery.length ? <DataTable headers={["Operation", "Trigger", "Status", "Candidates", "Cameras", "Started", "Duration"]}>{data.discovery.map((run) => <tr key={run.operation_id}><td><strong className="mono">{run.operation_id.slice(0, 12)}</strong></td><td>{title(run.trigger)}</td><td><StatusPill value={run.status} /></td><td>{run.counters?.discovered_candidates || 0}</td><td>{run.counters?.cameras_matched || 0}</td><td>{fmt(run.started_at || run.created_at)}</td><td>{run.started_at && run.finished_at ? `${Math.max(0, Math.round((new Date(run.finished_at).getTime() - new Date(run.started_at).getTime()) / 1000))}s` : "—"}</td></tr>)}</DataTable> : <EmptyState icon="radar" title="No discovery history" description="Completed and failed runs will appear here." />}</Panel>
    {scopeModal && <Modal title="Add discovery scope" description="Only addresses inside this subnet will be considered." onClose={() => setScopeModal(false)}><form className="form-grid" onSubmit={(event) => submitForm(event, async (form) => { if (await mutate(send("/api/v1/discovery-scopes", "POST", { interface_name: form.get("interface_name"), cidr: form.get("cidr"), rtsp_ports: String(form.get("rtsp_ports")).split(",").map((item) => Number(item.trim())), enabled: true }), "Discovery scope added")) setScopeModal(false); })}><Field label="Interface"><input name="interface_name" placeholder="enp2s0" required /></Field><Field label="Subnet"><input name="cidr" placeholder="192.168.20.0/24" required /></Field><Field label="RTSP ports" wide hint="Comma-separated ports"><input name="rtsp_ports" defaultValue="554, 8554" required /></Field><FormActions><button type="button" className="button secondary" onClick={() => setScopeModal(false)}>Cancel</button><button className="button">Add scope</button></FormActions></form></Modal>}
  </>;
}

function AssignmentModal({ deployment, cameras, close, mutate }: { deployment: Deployment; cameras: Camera[]; close: () => void; mutate: Mutate }) {
  const [selected, setSelected] = useState<Record<string, boolean>>({});
  const [apps, setApps] = useState<Record<string, string[]>>({});
  const choices = ["anpr", "vehicle_counting", "pedestrian_counting", "wrong_way", "illegal_parking"];
  return <Modal title={`Assign cameras to ${deployment.deployment_id}`} description="Each selected workload opens its own physical RTSP session." onClose={close} wide><form onSubmit={(event) => { event.preventDefault(); const assignments = cameras.filter((camera) => selected[camera.camera_id]).map((camera) => ({ camera_id: camera.camera_id, apps: apps[camera.camera_id]?.length ? apps[camera.camera_id] : ["vehicle_counting"], fps: 8, bundle_application: "runtime" })); void (async () => { if (await mutate(send(`/api/v1/deployments/${encodeURIComponent(deployment.deployment_id)}/assignments`, "POST", { assignments, idempotency_key: crypto.randomUUID() }), "Assignments committed")) close(); })(); }}><div className="assignment-list">{cameras.filter((camera) => camera.enabled && camera.state === "online").map((camera) => <div key={camera.camera_id} className={selected[camera.camera_id] ? "selected" : ""}><label className="camera-choice"><input type="checkbox" checked={Boolean(selected[camera.camera_id])} onChange={(event) => setSelected({ ...selected, [camera.camera_id]: event.target.checked })} /><span className="camera-glyph"><Icon name="camera" /></span><span><strong>{camera.friendly_name}</strong><small>{camera.camera_id}</small></span></label>{selected[camera.camera_id] && <div className="app-choices">{choices.map((choice) => <label key={choice}><input type="checkbox" checked={apps[camera.camera_id]?.includes(choice) || false} onChange={(event) => setApps({ ...apps, [camera.camera_id]: event.target.checked ? [...(apps[camera.camera_id] || []), choice] : (apps[camera.camera_id] || []).filter((item) => item !== choice) })} />{title(choice)}</label>)}</div>}</div>)}{!cameras.some((camera) => camera.enabled && camera.state === "online") && <EmptyState icon="camera" title="No assignable cameras" description="A camera must be enabled and successfully validated first." />}</div><FormActions><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button" disabled={!Object.values(selected).some(Boolean)}>Commit assignments</button></FormActions></form></Modal>;
}

function SolutionsPage({ data, mutate }: { data: Snapshot; mutate: Mutate }) {
  const [assign, setAssign] = useState<Deployment | null>(null);
  return <><PageHeader eyebrow="Application lifecycle" title="Solutions" description="Manage approved Solution Packs, camera assignments, desired revisions, and rollouts." />
    <div className="metric-grid three"><MetricCard label="Registered" value={data.deployments.length} hint="Trusted bundle templates" icon="boxes" /><MetricCard label="Synchronized" value={data.deployments.filter((item) => item.sync_state === "applied").length} hint="Desired equals applied" status={data.health?.components.secret_synchronization?.status} icon="check" /><MetricCard label="Out of sync" value={data.deployments.filter((item) => item.sync_state !== "applied").length} hint="Pending or failed revisions" status={data.deployments.some((item) => item.sync_state === "failed") ? "degraded" : "healthy"} icon="pulse" /></div>
    <Panel title="Deployments" subtitle="Curated bundles registered by the trusted installer" className="flush">{data.deployments.length ? <DataTable headers={["Solution", "Lifecycle", "Synchronization", "Revision", "Last error", "Actions"]}>{data.deployments.map((item) => <tr key={item.deployment_id}><td><strong>{item.deployment_id}</strong><small className="table-sub">{item.solution_id} · {item.namespace}</small></td><td><StatusPill value={item.lifecycle_intent} /></td><td><StatusPill value={item.sync_state} /></td><td><span className="revision-pair"><strong>{item.applied_revision ?? "—"}</strong><span>/</span>{item.desired_revision ?? "—"}</span><small className="table-sub">applied / desired</small></td><td>{item.last_error_code ? <span className="error-text">{item.last_error_code}</span> : <span className="muted">None</span>}</td><td><div className="table-actions"><button className="button small secondary" onClick={() => setAssign(item)}>Assign cameras</button>{item.lifecycle_intent === "Running" ? <ConfirmButton className="button small ghost-danger" message={`Stop ${item.deployment_id}?`} onConfirm={() => { void mutate(send(`/api/v1/deployments/${encodeURIComponent(item.deployment_id)}/stop`, "POST"), "Stop revision queued"); }}><Icon name="stop" size={14} /> Stop</ConfirmButton> : <button className="button small" onClick={() => void mutate(send(`/api/v1/deployments/${encodeURIComponent(item.deployment_id)}/start`, "POST"), "Start revision queued")}><Icon name="play" size={14} /> Start</button>}</div></td></tr>)}</DataTable> : <EmptyState icon="boxes" title="No Solution Packs registered" description="Register a reviewed bundle through the trusted installer/API. Raw YAML upload is intentionally unavailable." />}</Panel>
    <div className="callout info"><Icon name="eye" /><div><strong>Immutable desired state</strong><p>Camera credentials never appear in bundle previews or this UI. Applying assignments creates a new immutable desired revision.</p></div></div>
    {assign && <AssignmentModal deployment={assign} cameras={data.cameras} close={() => setAssign(null)} mutate={mutate} />}
  </>;
}

function ClusterPage({ data }: { data: Snapshot }) {
  const [tab, setTab] = useState("nodes"); const [telemetry, setTelemetry] = useState<TelemetryResponse | null>(null); const [nodeDetail, setNodeDetail] = useState<NodeView | null>(null); const cluster = data.cluster;
  const workload = cluster?.workloads;
  const loadTelemetry = async (name: string) => setTelemetry(await get(`/api/v1/cluster/workloads/${encodeURIComponent(name)}/telemetry`));
  return <><PageHeader eyebrow="ApexFabric runtime" title="K3s cluster" description="The same node, workload, networking, storage, event, and telemetry data as the original port-8088 console." />
    <div className="cluster-banner"><div><span className={cx("cluster-orb", cluster?.api.status)}><Icon name="cluster" size={26} /></span><div><span>K3s API</span><h2>{cluster?.api.status === "healthy" ? "Connected" : "Unavailable"}</h2><p>Single-node edge control plane · namespace apexfabric</p></div></div><StatusPill value={cluster?.status || "unavailable"} /></div>
    <div className="metric-grid five"><MetricCard label="Nodes ready" value={`${cluster?.nodes.items.filter((item) => item.ready).length || 0}/${cluster?.nodes.total || 0}`} icon="cluster" /><MetricCard label="Deployments" value={workload?.deployments.total || 0} hint={`${workload?.deployments.items.filter((item) => item.ready).length || 0} ready`} /><MetricCard label="Pods running" value={`${workload?.pods.items.filter((item) => item.phase === "Running").length || 0}/${workload?.pods.total || 0}`} /><MetricCard label="Storage claims" value={workload?.persistent_volume_claims?.total || 0} /><MetricCard label="Warning events" value={workload?.events?.items.filter((item) => item.type === "Warning").length || 0} /></div>
    <nav className="resource-tabs">{[["nodes", "Nodes"], ["deployments", "Deployments"], ["pods", "Pods"], ["services", "Services"], ["replicas", "ReplicaSets"], ["storage", "Storage"], ["events", "Events"]].map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</nav>
    <Panel className="flush cluster-table">
      {tab === "nodes" && (cluster?.nodes.items.length ? <DataTable headers={["Node", "Status", "Architecture", "Profile", "Qualification", "Camera streams", ""]}>{cluster.nodes.items.map((node) => <tr key={node.name}><td><strong>{node.name}</strong><small className="table-sub">{node.roles?.join(", ") || "control-plane, worker"}</small></td><td><StatusPill value={node.ready ? "Ready" : "Not ready"} /></td><td>{node.architecture || "—"}</td><td>{node.hardware_profile || "—"}</td><td><StatusPill value={node.qualified} label={node.qualified ? "Qualified" : "Not qualified"} /><small className="table-sub">{node.qualification_reason || ""}</small></td><td>{node.camera_streams.allocatable ?? "—"} / {node.camera_streams.capacity ?? "—"}<small className="table-sub">allocatable / capacity</small></td><td><button className="button small secondary" onClick={() => setNodeDetail(node)}>Details</button></td></tr>)}</DataTable> : <EmptyState icon="cluster" title="Node status unavailable" description="The edge UI remains available while K3s recovers." />)}
      {tab === "deployments" && (workload?.deployments.items.length ? <DataTable headers={["Deployment", "Ready", "Replicas", "Image", "Actions"]}>{workload.deployments.items.map((item) => <tr key={item.name}><td><strong>{item.name}</strong><small className="table-sub">{item.application || item.deployment_id}</small></td><td><StatusPill value={item.ready} label={item.ready ? "Ready" : "Progressing"} /></td><td>{item.ready_replicas}/{item.desired_replicas}<small className="table-sub">{item.available_replicas} available</small></td><td className="image-cell">{item.image || "—"}</td><td><button className="button small secondary" onClick={() => void loadTelemetry(item.name)}>Telemetry</button></td></tr>)}</DataTable> : <EmptyState title="No deployments" description="No managed Solution Pack workloads are present." />)}
      {tab === "pods" && (workload?.pods.items.length ? <DataTable headers={["Pod", "Phase", "Ready", "Restarts", "Node", "Created"]}>{workload.pods.items.map((item) => <tr key={item.name}><td><strong>{item.name}</strong><small className="table-sub">{item.application || item.deployment_id}</small></td><td><StatusPill value={item.phase} /></td><td>{item.ready ? "Yes" : "No"}</td><td>{item.restart_count}</td><td>{item.node || "Pending"}</td><td>{fmt(item.created_at)}</td></tr>)}</DataTable> : <EmptyState title="No pods" description="No managed Pods are present." />)}
      {tab === "services" && (workload?.services?.items.length ? <DataTable headers={["Service", "Type", "Cluster IP", "Ports"]}>{workload.services.items.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.type}</td><td className="mono">{item.cluster_ip || "—"}</td><td>{item.ports.join(", ") || "—"}</td></tr>)}</DataTable> : <EmptyState title="No services" description="No services are present in the product namespace." />)}
      {tab === "replicas" && (workload?.replica_sets?.items.length ? <DataTable headers={["ReplicaSet", "Desired", "Ready", "Available"]}>{workload.replica_sets.items.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.desired}</td><td>{item.ready}</td><td>{item.available}</td></tr>)}</DataTable> : <EmptyState title="No ReplicaSets" description="No ReplicaSets are present." />)}
      {tab === "storage" && (workload?.persistent_volume_claims?.items.length ? <DataTable headers={["Claim", "Status", "Capacity", "Storage class", "Retention"]}>{workload.persistent_volume_claims.items.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td><StatusPill value={item.phase} /></td><td>{item.capacity || "—"}</td><td>{item.storage_class || "default"}</td><td>{item.retention || "managed"}</td></tr>)}</DataTable> : <EmptyState title="No persistent claims" description="No retained workload storage is present." />)}
      {tab === "events" && (workload?.events?.items.length ? <DataTable headers={["Type", "Object", "Reason", "Message", "Count", "Last seen"]}>{workload.events.items.map((item, index) => <tr key={`${item.object}-${item.reason}-${index}`}><td><StatusPill value={item.type === "Warning" ? "warning" : "healthy"} label={item.type} /></td><td>{item.object}</td><td>{item.reason || "—"}</td><td className="event-message">{item.message || "—"}</td><td>{item.count}</td><td>{fmt(item.last_seen)}</td></tr>)}</DataTable> : <EmptyState title="No recent events" description="Kubernetes events will appear here." />)}
    </Panel>
    {nodeDetail && <Modal title={`Node report · ${nodeDetail.name}`} description="Controller qualification and reporter-discovered host capabilities" onClose={() => setNodeDetail(null)} wide><div className="content-grid equal"><Panel title="Qualification"><dl className="definition-list"><div><dt>Node readiness</dt><dd><StatusPill value={nodeDetail.ready ? "ready" : "unavailable"} /></dd></div><div><dt>Controller decision</dt><dd><StatusPill value={nodeDetail.qualified} label={nodeDetail.qualified ? "Qualified" : "Not qualified"} /></dd></div><div><dt>Reason</dt><dd>{nodeDetail.qualification_reason || "No controller reason reported"}</dd></div><div><dt>Report observed</dt><dd>{fmt(nodeDetail.reporter_observed_at)}</dd></div><div><dt>Hardware profile</dt><dd>{nodeDetail.hardware_profile || "—"}</dd></div><div><dt>Architecture</dt><dd>{nodeDetail.architecture || "—"}</dd></div></dl></Panel><Panel title="Discovered capabilities"><JsonView value={nodeDetail.capabilities || { status: "No ApexNodeStatus report" }} /></Panel></div></Modal>}
    {telemetry && <Modal title={`Workload telemetry · ${telemetry.deployment}`} description="Allowlisted health, readiness, metrics, and Kubernetes state" onClose={() => setTelemetry(null)} wide><div className="telemetry-head"><StatusPill value={telemetry.available ? "healthy" : "unavailable"} label={telemetry.available ? "Live" : "Unavailable"} />{telemetry.error && <span className="error-text">{telemetry.error}</span>}</div><div className="telemetry-grid"><Panel title="Health"><JsonView value={telemetry.health || { status: "unavailable" }} /></Panel><Panel title="Readiness"><JsonView value={telemetry.readiness || { ready: false }} /></Panel><Panel title="Kubernetes state"><JsonView value={telemetry.kubernetes || {}} /></Panel><Panel title="Metrics"><pre className="json-view">{telemetry.metrics || "No metrics response."}</pre></Panel></div></Modal>}
  </>;
}

function AlertsPage({ data, mutate }: { data: Snapshot; mutate: Mutate }) {
  const [filter, setFilter] = useState("active"); const [selected, setSelected] = useState<AlertItem | null>(null); const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  const visible = data.alerts.filter((item) => filter === "all" || (filter === "active" ? item.state !== "resolved" : item.state === filter));
  const inspect = async (alert: AlertItem) => { setSelected(alert); setNotifications(await safeGet(`/api/v1/alerts/${alert.alert_id}/notifications`, [])); };
  return <><PageHeader eyebrow="Operational response" title="Alerts" description="Review active conditions, acknowledge ownership, and inspect durable email delivery." />
    <div className="metric-grid three"><MetricCard label="Active" value={data.alerts.filter((item) => item.state === "active").length} icon="bell" /><MetricCard label="Acknowledged" value={data.alerts.filter((item) => item.state === "acknowledged").length} /><MetricCard label="Critical" value={data.alerts.filter((item) => item.state !== "resolved" && item.severity === "critical").length} status={data.alerts.some((item) => item.state !== "resolved" && item.severity === "critical") ? "degraded" : "healthy"} /></div>
    <div className="toolbar"><div className="segmented">{["active", "acknowledged", "resolved", "all"].map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{title(item)}</button>)}</div></div>
    <Panel className="flush">{visible.length ? <DataTable headers={["Alert", "Severity", "Source", "State", "Occurrences", "Last seen", ""]}>{visible.map((item) => <tr key={item.alert_id}><td><button className="primary-cell plain" onClick={() => void inspect(item)}><span><strong>{item.annotations.summary || item.alertname}</strong><small>{item.alertname}</small></span></button></td><td><StatusPill value={item.severity} /></td><td>{item.camera_id || item.service || "System"}<small className="table-sub">{item.use_case || ""}</small></td><td><StatusPill value={item.state} /></td><td>{item.occurrence_count}</td><td>{relative(item.last_seen_at)}</td><td><button className="icon-button" onClick={() => void inspect(item)}><Icon name="arrow" /></button></td></tr>)}</DataTable> : <EmptyState icon="check" title="No alerts in this view" description="Alertmanager and host-originated conditions will appear here." />}</Panel>
    {selected && <Modal title={selected.annotations.summary || selected.alertname} description={`${selected.alertname} · ${selected.camera_id || selected.service || "System"}`} onClose={() => setSelected(null)} wide><div className="alert-detail-head"><StatusPill value={selected.severity} /><StatusPill value={selected.state} /><span>First seen {fmt(selected.first_seen_at)}</span></div><div className="content-grid two-one"><div><Panel title="Alert details"><dl className="definition-list"><div><dt>Service</dt><dd>{selected.service || "—"}</dd></div><div><dt>Camera</dt><dd>{selected.camera_id || "—"}</dd></div><div><dt>Use case</dt><dd>{selected.use_case || "—"}</dd></div><div><dt>Occurrences</dt><dd>{selected.occurrence_count}</dd></div><div><dt>Last seen</dt><dd>{fmt(selected.last_seen_at)}</dd></div><div><dt>Acknowledged by</dt><dd>{selected.acknowledged_by || "—"}</dd></div></dl>{selected.state === "active" && <button className="button" onClick={() => void (async () => { if (await mutate(send(`/api/v1/alerts/${selected.alert_id}/acknowledge`, "POST"), "Alert acknowledged")) setSelected(null); })()}>Acknowledge alert</button>}</Panel></div><Panel title="Email delivery"><div className="notification-list">{notifications.map((item) => <div key={item.notification_id}><StatusPill value={item.state} /><span><strong>{title(item.type)} notification</strong><small>{item.attempt_count} attempt{item.attempt_count === 1 ? "" : "s"} · {item.sent_at ? `Sent ${fmt(item.sent_at)}` : item.next_attempt_at ? `Retry ${fmt(item.next_attempt_at)}` : "Not sent"}</small></span></div>)}{!notifications.length && <EmptyState title="No notifications" description="No email delivery was created for this alert." />}</div></Panel></div></Modal>}
  </>;
}

function OperationsPage({ data }: { data: Snapshot }) {
  const [query, setQuery] = useState(""); const visible = data.audit.filter((item) => `${item.action} ${item.actor} ${item.target_id} ${item.result}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader eyebrow="Audit and recovery" title="Activity" description="A redacted, append-only view of management changes and automated recovery actions." /><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search activity" /></div><Panel className="flush">{visible.length ? <DataTable headers={["Time", "Action", "Target", "Actor", "Result", "Request ID"]}>{visible.map((item) => <tr key={item.audit_id}><td>{fmt(item.created_at)}</td><td><strong>{title(item.action.replaceAll(".", " "))}</strong></td><td>{item.target_type}<small className="table-sub mono">{item.target_id}</small></td><td>{item.actor}</td><td><StatusPill value={item.result} /></td><td className="mono">{item.request_id.slice(0, 16)}</td></tr>)}</DataTable> : <EmptyState icon="history" title="No matching activity" description="Management audit events will appear here." />}</Panel></>;
}

function SettingsPage({ data, mutate }: { data: Snapshot; mutate: Mutate }) {
  return <><PageHeader eyebrow="Site configuration" title="Settings" description="Review site identity, discovery boundaries, security posture, and software endpoints." />
    <div className="content-grid equal"><Panel title="Site identity"><dl className="definition-list"><div><dt>Site ID</dt><dd>{data.site?.site_id || "Not configured"}</dd></div><div><dt>Edge ID</dt><dd>{data.site?.edge_id || "—"}</dd></div><div><dt>Display name</dt><dd>{data.site?.display_name || "—"}</dd></div><div><dt>Timezone</dt><dd>{data.site?.timezone || "—"}</dd></div><div><dt>Configuration revision</dt><dd>{data.site?.config_revision ?? "—"}</dd></div></dl></Panel><Panel title="Security posture"><div className="security-list"><div><Icon name="check" /><span><strong>Loopback management bind</strong><small>The API is not exposed directly to the LAN.</small></span></div><div><Icon name="check" /><span><strong>Write-only camera credentials</strong><small>AES-256-GCM encrypted at rest.</small></span></div><div><Icon name="check" /><span><strong>Scoped Kubernetes access</strong><small>Only bounded product resources are available.</small></span></div><div className="pending"><Icon name="warning" /><span><strong>Management proxy authentication</strong><small>Required before management-LAN exposure.</small></span></div></div></Panel></div>
    <Panel title="Discovery boundaries" subtitle="Only these interfaces and CIDRs can be scanned" className="flush">{data.scopes.length ? <DataTable headers={["Interface", "CIDR", "RTSP ports", "State", ""]}>{data.scopes.map((scope) => <tr key={scope.scope_id}><td><strong>{scope.interface_name}</strong></td><td className="mono">{scope.cidr}</td><td>{scope.rtsp_ports.join(", ")}</td><td><StatusPill value={scope.enabled} label={scope.enabled ? "Enabled" : "Disabled"} /></td><td><ConfirmButton className="button small ghost-danger" message={`Remove discovery scope ${scope.cidr}?`} onConfirm={() => { void mutate(send(`/api/v1/discovery-scopes/${scope.scope_id}`, "DELETE"), "Discovery scope removed"); }}>Remove</ConfirmButton></td></tr>)}</DataTable> : <EmptyState icon="radar" title="No boundaries configured" description="Add a discovery scope from the Discovery page." />}</Panel>
    <Panel title="Local endpoints"><dl className="definition-list endpoints"><div><dt>Management UI</dt><dd>http://127.0.0.1:8088</dd></div><div><dt>Edge metrics</dt><dd>Configured host metrics listener</dd></div><div><dt>Alert receiver</dt><dd>Host-only port 8090</dd></div><div><dt>Grafana</dt><dd>ClusterIP via approved management proxy</dd></div></dl></Panel>
  </>;
}

export default function App() {
  const initialPage = (window.location.hash.replace("#", "") || "overview") as Page;
  const [page, setPage] = useState<Page>(pages.flatMap((group) => group.items).some((item) => item.id === initialPage) ? initialPage : "overview");
  const [data, setData] = useState<Snapshot>(emptySnapshot); const [loading, setLoading] = useState(true); const [lastRefresh, setLastRefresh] = useState<Date | null>(null); const [toast, setToast] = useState<{ message: string; error?: boolean } | null>(null); const [mobileNav, setMobileNav] = useState(false);
  const reload = useCallback(async () => {
    const [health, site, cameras, discovery, scopes, deployments, cluster, alerts, audit] = await Promise.all([
      safeGet<HealthResponse | null>("/api/v1/health", null), safeGet<Site | null>("/api/v1/site", null), safeGet<Camera[]>("/api/v1/cameras", []), safeGet<DiscoveryRun[]>("/api/v1/discovery-runs?limit=50", []), safeGet<DiscoveryScope[]>("/api/v1/discovery-scopes", []), safeGet<Deployment[]>("/api/v1/deployments", []), safeGet<ClusterResponse | null>("/api/v1/cluster", null), safeGet<AlertItem[]>("/api/v1/alerts?limit=200&include_resolved=true", []), safeGet<AuditItem[]>("/api/v1/audit-events?limit=200", []),
    ]);
    setData({ health, site, cameras, discovery, scopes, deployments, cluster, alerts, audit }); setLastRefresh(new Date()); setLoading(false);
  }, []);
  useEffect(() => { void reload(); const timer = window.setInterval(() => void reload(), 5000); return () => window.clearInterval(timer); }, [reload]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 3500); return () => window.clearTimeout(timer); }, [toast]);
  const go = (value: Page) => { window.location.hash = value; setPage(value); setMobileNav(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const mutate: Mutate = async (promise, success) => { try { await promise; setToast({ message: success }); await reload(); return true; } catch (error) { setToast({ message: error instanceof Error ? error.message : "Operation failed", error: true }); return false; } };
  const current = useMemo(() => pages.flatMap((group) => group.items).find((item) => item.id === page), [page]);
  return <div className="app-shell">
    <aside className={cx("sidebar", mobileNav && "open")}><div className="brand"><span className="brand-mark"><span /></span><div><strong>TVT</strong><small>Edge operations</small></div></div><nav>{pages.map((group) => <div key={group.group} className="nav-group"><span>{group.group}</span>{group.items.map((item) => <button key={item.id} className={page === item.id ? "active" : ""} onClick={() => go(item.id)}><Icon name={item.icon} /><span>{item.label}</span>{item.id === "alerts" && data.alerts.some((alert) => alert.state !== "resolved") && <i className="nav-count">{data.alerts.filter((alert) => alert.state !== "resolved").length}</i>}</button>)}</div>)}</nav><div className="sidebar-foot"><div className="edge-identity"><span className={cx("connection-dot", data.health?.status)} /><div><strong>{data.site?.edge_id || "Edge service"}</strong><small>{data.health ? title(data.health.status) : "Connecting"}</small></div></div><span>TVT Runtime 0.1.0</span></div></aside>
    <div className="app-main"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Toggle navigation"><span /><span /><span /></button><div className="breadcrumb"><span>TVT</span><i>/</i><strong>{current?.label}</strong></div><div className="top-actions"><span className="refresh-time">{lastRefresh ? `Updated ${relative(lastRefresh.toISOString())}` : "Connecting"}</span><button className={cx("icon-button", loading && "spinning")} onClick={() => void reload()} aria-label="Refresh"><Icon name="refresh" /></button><span className="operator-avatar">OP</span></div></header><main className="page-content">{loading && <div className="loading-bar" />}{page === "overview" && <OverviewPage data={data} go={go} />}{page === "cameras" && <CamerasPage data={data} mutate={mutate} />}{page === "discovery" && <DiscoveryPage data={data} mutate={mutate} />}{page === "solutions" && <SolutionsPage data={data} mutate={mutate} />}{page === "cluster" && <ClusterPage data={data} />}{page === "alerts" && <AlertsPage data={data} mutate={mutate} />}{page === "operations" && <OperationsPage data={data} />}{page === "settings" && <SettingsPage data={data} mutate={mutate} />}</main></div>
    {mobileNav && <button className="nav-backdrop" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}{toast && <div className={cx("toast", toast.error && "error")}><Icon name={toast.error ? "warning" : "check"} /><span>{toast.message}</span></div>}
  </div>;
}
