apiVersion: v1
kind: ConfigMap
metadata:
  name: tvt-grafana-loki-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: tvt-observability
data:
  loki.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://tvt-loki-gateway.monitoring.svc.cluster.local
        isDefault: false
        editable: false
